### ISSUE TITLE
Digtron HV power connector not working well or at all

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#100]
Digtron HV power connector depends on meta value `HV_network`.
`tier .. "_network"` metadata keys were removed partially in #80 and completely in #96.

Digtron does not actually use that value for anything but instead simply uses that to check if power connector is connected to valid HV network.

https://github.com/minetest-mods/digtron/blob/843dbd227658a93ee4df791bfdd3d136ee7adf85/util_execute_cycle.lua#L233-L237
```lua
for _, power_connector in pairs(layout.power_connectors) do
	if power_connector.meta.fields.HV_network and power_connector.meta.fields.HV_EU_input then
		power_inputs[power_connector.meta.fields.HV_network] = tonumber(power_connector.meta.fields.HV_EU_input)
	end
end
```

**This can be patched within technic mod by adding some `compatibility_hacks.lua` with following contents:**
```lua
local digtron_technic_run = minetest.registered_nodes["digtron:power_connector"].technic_run
minetest.override_item("digtron:power_connector",{
        technic_run = function(pos, node)
                local network_id = technic.pos2network(pos)
                local sw_pos = network_id and technic.network2sw_pos(network_id)
                local meta = minetest.get_meta(pos)
                meta:set_string("HV_network", sw_pos and minetest.pos_to_string(sw_pos) or "")
                return digtron_technic_run(pos, node)
        end,
})
```

**Or that check could be removed completely from digtron mod:**
```patch
   for _, power_connector in pairs(layout.power_connectors) do
-- 	if power_connector.meta.fields.HV_network and power_connector.meta.fields.HV_EU_input then
-- 		power_inputs[power_connector.meta.fields.HV_network] = tonumber(power_connector.meta.fields.HV_EU_input)
++ 	if power_connector.meta.fields.HV_EU_input then
++ 		power_inputs[_] = tonumber(power_connector.meta.fields.HV_EU_input)
  	end
   end
```

**Or `tier .. "_network"` meta can be restored for machines registered without some `network_v2_ready = true` flag.** probably bad idea...

**Or `tier .. "_network"` meta can be restored for everything.** not best solution especially when fact is that digtron does not need or use meta value in question.

**Comment by BuckarooBanzay** [comment]
> Or that check could be removed completely from digtron mod:

Development on the `digtron` mod has pretty much halted and the `digpocalypse` branch that promised an entirely new digtron hasn't received much love either...

I'm tempted to fork that thing and rewrite some stuff but i currently don't have the time for that.

**Comment by S-S-X** [comment]
Revisit this after other updates (#96) are done, more info in PR comments about old bug causing problems with power connector.
