### ISSUE TITLE
.luacheckrc contains unnecessary ignores

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#105]
Many of ignored linter checks should fail and not get ignored.

Failing things should be checked in code not by disabling checks.
Some ignores are of course fine but most ignores that target specific source files in current .luacheckrc are not fine at all, currently there's things that can allow a lot of crash causing simple mistakes to slip through.

**Remove these ignores** and only add back ones really needed (almost sure that none of these are really needed) and issue cannot be fixed:
https://github.com/mt-mods/technic/blob/264029a66f06f945e305de106aca6ad8354d5850/.luacheckrc#L32-L47

Also before adding any of those or like those always **consider adding specific ignore rule through source code comments**, that way it is at least visible when code is modified.
https://luacheck.readthedocs.io/en/stable/inline.html

**Comment by OgelGames** [comment]
Totally agree with you there, never realized that so much was being ignored...

Also think this should be fixed:
https://github.com/mt-mods/technic/blob/264029a66f06f945e305de106aca6ad8354d5850/.luacheckrc#L2

**Comment by OgelGames** [comment]
I fixed what I could, only leaving a few files ignored to prevent merge conflicts:
https://github.com/mt-mods/technic/blob/a2999de5ee7e2951505b7bb8571a1fdf1b79fa16/.luacheckrc#L31-L38

I must say, there is some bad code in there, can't even imagine how long it would take to clean it all up 😖 The worst I found was this one, with a line length of over 430:
https://github.com/mt-mods/technic/blob/264029a66f06f945e305de106aca6ad8354d5850/technic_cnc/cnc_api.lua#L331

I also fixed a bug with the wood grinding recipes, where there were some wrong node names, and discovered this interesting unused thing: https://github.com/mt-mods/technic/blob/master/technic/machines/MV/power_radiator.lua

**Comment by S-S-X** [comment]
> I must say, there is some bad code in there, can't even imagine how long it would take to clean it all up

Yeah, in these cases it is probably better to just move ignores into source files. Snippet from luacheck docs:

> Part of the file affected by inline option dependes on where it is placed. If there is any code on the line with the option, only that line is affected; otherwise, everything till the end of the current closure is. In particular, inline options at the top of the file affect all of it:

If scope for required ignores is more limited then put ignores in that closure.

If there's really a lot of things that should be ignored and no useful closures then use `-- luacheck: push` and `-- luacheck: pop` with clearly visible comments about it.

**Comment by OgelGames** [comment]
There wasn't anything that I couldn't fix, I was just talking about all the bad code throughout the mod. I edited my comment with better wording 😉

**Comment by BuckarooBanzay** [comment]
wow, that was fast!
The initial `.luacheckrc` config came from upstream https://github.com/minetest-mods/technic/pull/545 and i think he didn't want to start fixing those bugs because that would have made the PR too big (and no one wants to touch big PR's in the technic repo it seems...)

**Comment by S-S-X** [comment]
Just noticed a bit weird thing, either all CI actions use .luacheckrc from master or there's something other weirdness going on:
https://github.com/mt-mods/technic/pull/96/checks
That was before I merged master into network-ng and there luacheck linter is complaining about line lengths, so when those actions were executed network-ng branch still had `max_line_length = 999`.
