### ISSUE TITLE
Rewrite all machine/cable registration functions to have generic format

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#117]
Also see #115 comments.

This would be very good thing for both technic mod itself and for other mods that like to use API functions provided by technic mods.
Currently there's not yet too many mods around using technic API, at least not publicly visible, I was digging large part of internet few months ago looking for these and found just few.
However with good enough API there would be a lot of potential for external mods implementing more machines / cables / something.

Currently API is not that good for external use and could be significantly improved for internal use to reduce code and make parameters and naming uniform.

Currently naming seems to mostly follow some unwritten guidelines so it should be possible to just implement API helpers and remove extra code. Might require renaming some things (textures mostly).

**Comment by OgelGames** [comment]
Probably should do the same with the chests register function... 🤔

**Comment by S-S-X** [comment]
Also updated registration for power tools and network cables. Very basic chest registration API is merged.
Some documentation updated at #237
