### ISSUE TITLE
Use node timer for self contained injector

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#120]
Don't see any reason why SCI can't use node timer, would also make it easier to add a on/off toggle. Code could also be cleaned up a bit too, particularly the `inject_items` function...

**Comment by S-S-X** [comment]
Could also add this sci node timer start to cleanup lbm #119

**Comment by OgelGames** [comment]
> Could also add this sci node timer start to cleanup lbm

I'd say it should be kept separate, I think that LBM should be only for network cleanup, and that the name should be changed to reflect that.

**Comment by S-S-X** [comment]
> it should be kept separate

Yeah, probably you're right, SCI is pretty far from machines.

> the name should be changed to reflect that.

If you meant metadata cleanup I think name is fine as it is not simply network specific things, it is for metadata cleanup. Mixed both directly network related, node specific storage and informational data that is not needed anymore so plain "metadata cleanup" seemed to be best name there. But true that everything there somehow relates to power networks.

Well, now there's also switching station nodetimer startup so should it be "technic:metadata_cleanup_with_switch_nodetimer_activation"? I'd say it does not have to be that specific as LBM code is pretty straightforward and easy to read, maybe few comments in LBM code could help.

**Comment by OgelGames** [comment]
> maybe few comments in LBM code could help.

👍 It only really matters when reading the code anyway.
