### ISSUE TITLE
Nuclear reactor meltdown crash in vacuum

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#123]
Steps:
* Build working reactor to vacuum and start it
* Cause meltdown by any means ~Dig walls and wait until vaporized water causes meltdown~
* Crash because group:technic_machine ABM gets called for technic:corium_source

Basically this is what causes ABM call with invalid node:
https://github.com/mt-mods/technic/blob/1113c93a2609afee8305541d833d53343153e888/technic/machines/HV/nuclear_reactor.lua#L213-L216

Mitigation:
Add check for node name to ABM to make sure node is actually registered technic machine.

There was such test for some time but check was removed because situation should not be possible if ABM would be only called for group:technic_machine.
Check was added here: https://github.com/mt-mods/technic/commit/d7882dbcc0d351aae1556db3542146cb4059c1c5
And removed here: https://github.com/mt-mods/technic/commit/8e0a6ea31397a56b2fb38330ca1fd61c52c7b5cc
Code for that check was not actually never merged to master.

Engine issue: https://github.com/minetest/minetest/issues/8378

**Comment by BuckarooBanzay** [comment]
i think that can be closed, the check was added by SX and seems to be working :+1:
