### ISSUE TITLE
Detach regression/unit tests from technic repository

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#130]
When I first added unit test framework for technic it was just copied from my [metatool mod](https://github.com/S-S-X/metatool) and then extended/modified to allow testing technic network behavior and to allow writing unit tests for network handler functions.

Now I've copied some stuff I've added for technic back to metatool repo and further extended framework there (adding ItemStack, MetaDataRef and few more core libraries)
Some of that stuff is visible here: https://github.com/S-S-X/metatool/pull/61

This framework has been growing to already allow testing a lot of things that utilize minetest core libraries, it might or might contain bugs and does not have tests for itself. Having this thing in multiple repositories is not good for development or reuse.

What would be good way to detach minetest unit test framework from technic repository?
Possible options:
* New repository for framework and pull engine stuff/fixtures as submodule for unit testing.
   Git submodule would allow easier development for testing but has a lot of other not so nice things.
* New repository for framework, build installable packages and distribute those through... something?
   This sounds like better approach and allows building technic mod packages without including all that test stuff.

Opinions / suggestions?

**Comment by BuckarooBanzay** [comment]
> New repository for framework and pull engine stuff/fixtures as submodule for unit testing.
Git submodule would allow easier development for testing but has a lot of other not so nice things.

This would be straight-forward and updateable/testable with the dependabot/renovate tool

> New repository for framework, build installable packages and distribute those through... something?
This sounds like better approach and allows building technic mod packages without including all that test stuff.

Lua does not have a standard way of "artifacts" or "deliverables" as far as i'm aware :thinking: 

IMO: submodule sounds good and it does not need to be checked (`git submodule init`) out if one would just download and use the mod :+1:

**Comment by S-S-X** [comment]
I'll try to isolate engine / library part, already did that for metatool project so next should just make technic tests work with same thing.
After that it should be just simple rm -rf spec/fixtures/minetest and add submodule there.

**Comment by S-S-X** [comment]
Added https://github.com/mt-mods/mineunit

**Comment by S-S-X** [comment]
Tested with metatool, seems to work just fine. Just add `submodules: true` (or `submodules: recursive` if needed) for checkout job.
https://github.com/S-S-X/metatool/pull/61/commits/30500d6321da93c32ff893e25bed7c3967f8289f
