### ISSUE TITLE
Unused textures

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#142]
As of https://github.com/minetest/minetest/commit/98faeac5a7b382e5d7ce0474bf7d52fc5975a23c, mod textures are loaded recursively, which means any textures in subfolders are also loaded.

In the case of technic, the textures in all of these subfolders are unnecessarily loaded (255 textures, 979,092 bytes):
- https://github.com/mt-mods/technic/tree/master/concrete/textures/x32
- https://github.com/mt-mods/technic/tree/master/technic/textures/hires
- https://github.com/mt-mods/technic/tree/master/technic/textures/technicx32
- https://github.com/mt-mods/technic/tree/master/technic_chests/textures/old
- https://github.com/mt-mods/technic/tree/master/technic_chests/textures/x32
- https://github.com/mt-mods/technic/tree/master/technic_worldgen/textures/x32

Either the textures can be removed completely, or they can be moved into subfolders prefixed with "`.`" or "`_`" (and also excluded from the release export).

**Comment by S-S-X** [comment]
Does this actually affect server instance in any way? Probably it will use more memory but should be fairly easy to actually check that with massif.
Actual textures or other media should not be affected at all because priority seems to favor media files closest to root directory.

previous commit to test against: https://github.com/minetest/minetest/commit/9c7340104a7ec4007e3dfe0bb4482f3c8f9878e0

**Comment by OgelGames** [comment]
To be honest I don't know much about how MT handles textures, it might not have any significant effect at all, but just having so many unused files sitting there doesn't make much sense to me...

Maybe not all of them should be removed, just the ones that are not used at all, keeping the x32 versions.

**Comment by S-S-X** [comment]
Would it be possible to provide texture mod in modpack for hi resolution textures?

**Comment by OgelGames** [comment]
> Would it be possible to provide texture mod in modpack for hi resolution textures?

Hmm... Not sure how a texture mod would work, but it would certainly be possible to create a separate texture pack... 🤔

**Comment by S-S-X** [comment]
> Probably it will use more memory but should be fairly easy to actually check that with massif.

Tested and it does only seem to cause very short load time spike which is released immediately.
Tested with some fairly large textures :smile: 

![screenshot_20201221_081732](https://user-images.githubusercontent.com/50966843/102746110-3a5f9580-4366-11eb-9482-55f02d0080a1.png)

**Comment by BuckarooBanzay** [comment]
> Either the textures can be removed completely, or they can be moved into subfolders prefixed with "." or "_" (and also excluded from the release export).

+1 for removal, i don't see how they make sense there..
