### ISSUE TITLE
Stainless steel ingot looks different in 5.4.0-dev

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#145]
In Minetest 5.3.0:
![screenshot_1](https://user-images.githubusercontent.com/48543043/102745964-5dfbfd80-43b1-11eb-8e8b-0ff4add92c1d.png)

In 5.4.0-dev-af22dd86e:
![screenshot_2](https://user-images.githubusercontent.com/48543043/102745974-618f8480-43b1-11eb-8dc3-6e0f63554f28.png)

All other ingots (and AFAIK all other textures) look the same.

**Comment by S-S-X** [comment]
:eyes: where that comes from?

**Comment by OgelGames** [comment]
> correct texture is here

Interesting... 👀 

> Incorporate into #142

👍
