### ISSUE TITLE
Problems with dependencies

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#163]
Technic mod lists `screwdriver` as optional but crashes during loading if `screwdriver` is disabled.
It might be possible to fix this while keeping `screwdriver` optional.

If `moreores` is disabled silver is not available and many recipes are broken.
Moreores is listed as dependency in README.md and should be added to `mod.conf` dependencies too.

**Comment by BuckarooBanzay** [comment]
related: https://github.com/minetest-mods/technic/issues/582
