### ISSUE TITLE
Fix max_lag stuff

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#166]
Must be fixed if this gets merged https://github.com/minetest/minetest/pull/11077
Should be fixed anyway even if above does not get merged.

Not technically bug yet... there was no wanna-be-bug label...

Stuff that must be "fixed" is here:
https://github.com/mt-mods/technic/blob/master/technic/max_lag.lua

**Comment by BuckarooBanzay** [comment]
possible "fix" is just to return a default value if the parsing fails: #192 (fixes #191 in the short term)

Another fix would be to not rely on that value at all, its used in the radiation-code (to disable the cpu-heavy raycasting operations on high lag)  and in the switching-station globalstep (to kinda-dynamically reduce the globalstep work).
