### ISSUE TITLE
merge "monitoring_technic" into technic mod

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#172]
I'd like to merge the `monitoring_technic` (https://github.com/minetest-monitoring/monitoring_technic) mod into the actual `technic` mod with an optional dependency on `monitoring`.

Objections/Suggestions for useful additional metrics while i'm at it?

**Comment by S-S-X** [comment]
Keep it isolated and self contained internal API without too tight integration.
By isolated I don't mean just code / API but also actual files: keep lua files separated from other technic stuff in separate directory.

Not sure if it should be separate mod included in technic modpack or directly included into technic mod... maybe think about that for a moment:
* why it should be another mod included in technic modpack and not directly included into technic mod?
* why it should be directly included into technic mod and not another mod included in technic modpack?

**Comment by OgelGames** [comment]
To me it makes more sense to keep it separate, because I think most users would not want it, and all the other `monitoring_x` mods are separate from their mods (afaik).

**Comment by BuckarooBanzay** [comment]
fair points, closing this in favor of a standalone mod
