### ISSUE TITLE
mtinfo workflow action fails

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#184]
@BuckarooBanzay you're probably most familiar with mtinfo stuff.

Any idea why compiling mtinfo does not work currently?

**Comment by BuckarooBanzay** [comment]
Yeah, sorry: i introduced a setting to actually enable it.
The setting is added in #182 here:
https://github.com/mt-mods/technic/pull/182/commits/0ca7122d12e55b304b2fba196c55fc68c72378ab#diff-f0dba9b4d3227f842db09302a6e5613f234d9d669e7e40713adf41c916fce900R5

(i think that should be ready to merge :thinking:)

**Comment by BuckarooBanzay** [comment]
merged it, should now be fixed in the `master` branch, sorry for the trouble...
