### ISSUE TITLE
Machines don't support item groups

### ISSUE THREAD

**Issue by FriendlyGamer** [mt-mods/technic#201]
Hi there, I was attempting to extend my addon mod for this mod and I ran into a unclear issue. I cannot get grouped recipes to function on the compressor. 

Here is the exact recipe I was trying to add from my mod... 

> -- Compressor Recipes
> local recipes = {
> 	{"group:seed 8", "technic_addons:seedoil"},
> }
> for _, data in pairs(recipes) do
> 	technic.register_compressor_recipe({input = {data[1]}, output = data[2]})
> end

So the concern in question was "group:seed". 

Is it entirely possible to have this resolved please? 

Thanks in advance. :)

**Comment by OgelGames** [comment]
This is a known problem with all machines, technic recipes don't have support for groups.
https://github.com/mt-mods/technic/blob/38163960f1673af5d7d2233e1f80e1d264721859/technic/machines/register/grindings.lua#L54-L55

> Is it entirely possible to have this resolved please?

Yes, it can be fixed by adding support for groups, it's just that no one has done it yet...

**Comment by S-S-X** [comment]
Should this be included into v2.0 milestone?

Looking quickly through recipe registration stuff it feels like there's a lot that could be improved but it would probably cause some changes to actual API.

For one, public functions `technic.register_<insert machine name>_recipe` in my opinion are unnecessary wrappers just making API footprint larger without really providing that much. Exactly unnecessary wrappers like that make API way harder to understand even while those actually just add single field.

In my opinion to provide useful and easy to use API for recipe registration there should not be public "helpers" or wrappers.
Just API functions necessary for registering recipes: probably at most `technic.register_recipe_type(...)` and `technic.register_recipe(...)`.

**Comment by BuckarooBanzay** [comment]
> Should this be included into v2.0 milestone?

Sure, why not, but i think i could also be introduced later and without breaking any api (if it is just _additional_ support for groups and not renaming functions)

**Comment by OgelGames** [comment]
I don't see the API changing too drastically, the extra wrappers can still be kept for compatibility (with deprecation messages added), so it *could* be done without breaking anything.

I think it would still be good to add it to 2.0 though, as it shouldn't take much code to add. (unified inventory has some code that handles groups)
