### ISSUE TITLE
compatibility with upstream `nodedef.technic_no_network` function stub

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#206]
PR in the "official" technic mod here: https://github.com/minetest-mods/technic/pull/592

Checks if there is a `technic_no_network` function available on the node definition for a custom infotext

**Comment by S-S-X** [comment]
I have feeling that approach presented in pull request is not good way to handle infotext as is.
If needed it can be easily added here but would be better to take a look at underlying issue and see if there's better ways to fix it and then propose alternative.

**Comment by S-S-X** [comment]
Commented on upstream PR about how to avoid introducing duplicate callback with different name.

**Comment by S-S-X** [comment]
Also correct place to implement possible changes is here: https://github.com/mt-mods/technic/blob/aaf4f4768e6258203292164407e3e06fa8da5267/technic/machines/network.lua#L196-L212
