### ISSUE TITLE
Integration tests failing

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#209]
Minetest integration tests fail because minetest engine cannot find all required libraries on startup:

```
Status: Downloaded newer image for registry.gitlab.com/minetest/minetest/server:latest
Error loading shared library libzstd.so.1: No such file or directory (needed by /usr/local/bin/minetestserver)
```

**Comment by S-S-X** [comment]
See for example #207 and #208 integration test results:
https://github.com/mt-mods/technic/pull/207/checks?check_run_id=3524592169#step:3:31
https://github.com/mt-mods/technic/pull/208/checks?check_run_id=3527306649#step:3:32

**Comment by BuckarooBanzay** [comment]
Looks like they didn't update the `latest` docker image after merging this: https://github.com/minetest/minetest/pull/10788 :confused:

**Comment by BuckarooBanzay** [comment]
Fixed here: https://github.com/minetest/minetest/pull/11596

**Comment by S-S-X** [comment]
Tested and tests seems to work again, thanks 👍
