### ISSUE TITLE
Prevent CNC from accepting non-cuttable node/items

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#212]
Related: https://github.com/pandorabox-io/in-game/issues/130

**Comment by S-S-X** [comment]
I believe this should not be done for multiple reasons:
* All other machines accept nodes they cant handle
    * Arguably this could be fixed by changing all machines instead of just CNC
* It discourages building proper sorting and encourages having factories without sorting
    * This reduces challenges and choices provided by pipeworks.
    * Also indirectly has very high chance to encourage high memory and cpu demand setups more.
* It does not have zero cost (you could argue that it can be cached but so can everything else)

Not sure if I did take everything into account there, is there something available / possible that would address these concerns?

**Comment by OgelGames** [comment]
Yeah, I agree, particularly your second point. This can probably be closed.
