### ISSUE TITLE
Inefficient LV Lights

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#216]
The LV lights generate quite a lot of lag:

![Screenshot_2021-10-13_13-30-43](https://user-images.githubusercontent.com/39065740/137124690-aa3eda08-a7c4-40c8-86cd-c36524b8dd60.png)
(LV Circuit with 8 thermal generators and 8 LV LED's/Lights)

I haven't looked at the code but i think some of the issues can be addressed with VManips and possible batching/async execution...

**Comment by S-S-X** [comment]
Peanut just reported same / very similar problem. This really needs some optimization for performance, I was watching network reports and 7 gen 16 lamp 1 battery reported around 230-270ms execution time while average for other 80 networks were around 0.5ms and worst large machine network was jumping between 10ms-20ms.

**Comment by S-S-X** [comment]
Random few seconds delay for each lamp to spread out load?
That would be very simple and wont require nodetimers.

Just that alone however wont be able to restore missing lights, however after turning on/off in loaded areas it should be enough to do restoration only in active areas. So maybe still nodetimers unless there's some good way to check if area is active during technic_run.

**Comment by S-S-X** [comment]
Could also try to go with vm which is already used by networks.
Get vm handle before network run loop, collect updates and execute all at once after network loop.
That could then also be extended to other node swapping done for machines.
