### ISSUE TITLE
Remove wrench from modpack

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#253]
Also discussed at #251 

Moved to (with some history editing/cleanup, mostly intact however) https://github.com/mt-mods/wrench

TODO:
- [x] Issue / PR for configuration update: enable crafting by default but allow disabling https://github.com/mt-mods/wrench/pull/2
- [ ] Technic documentation cleanup, remove+write new or move documentation to new repo
- [ ] Delete [wrench](https://github.com/mt-mods/technic/tree/master/wrench) from technic modpack
- [x] `grep` (or use whatever text search tool) to verify that there's no references to wrench. If there's any, handle those somehow.
- [ ] [Technic v2.0](https://github.com/mt-mods/technic/milestone/1) ContentDB release with new wrench ContentDB package https://github.com/mt-mods/wrench/issues/1

**Comment by BuckarooBanzay** [comment]
Those are the only references for the `wrench` keyword:
```
# grep wrench technic -rn
technic/config.lua:15:	enable_wrench_crafting = "false",
technic/spec/fixtures/technic.conf:11:enable_wrench_crafting = true
technic/doc/tools.md:67:<img src="../../wrench/textures/technic_wrench.png"/>
```

The other folders are clean

**Comment by Athozus** [comment]
I support that moving. Note that `ack` (debian package: `ack-grep`) is useful for that searches. Can work on that relatively soon.

**Comment by S-S-X** [comment]
> I support that moving. Note that `ack` (debian package: `ack-grep`) is useful for that searches. Can work on that relatively soon.

I think basic cleanup is already done
Wrench mod is somewhere between ready and semi-ready for deployment at https://github.com/mt-mods/wrench
There's draft package at ContentDB https://content.minetest.net/packages/mt-mods/wrench/

What would be nice to change: all those overrides that were added replaced with this https://github.com/minetest/minetest/pull/12614 (not released yet).
However I'm not exactly sure how to efficiently replace all the items again with wrench but it would not have to mess with all the other mods item placement callbacks.

**Comment by OgelGames** [comment]
I've been eyeing this up for a while, there's a few things with the new version that I wasn't quite happy with it was made, and I'd like to resolve them myself.

Also there's the mineunit PRs sitting there, which I've since changed my mind about (I support them now). On that topic, it could be good to create a generic test that adds its own test node (using the API), rather than pulling in mods to test their nodes.

I ticked off the `grep` task, because there has never been any references to the wrench in technic, besides the mod itself (I did check again though).

**Comment by Athozus** [comment]
Still missing to do : move new commits that occurred on `wrench/` directory to `mt-mods/wrench`. The problem is that wrench repo is ahead of 1 commit which is complicating the process.

**Comment by S-S-X** [comment]
> Still missing to do : move new commits that occurred on wrench/ directory to mt-mods/wrench. The problem is that wrench repo is ahead of 1 commit which is complicating the process.

Wrench repo is very different thing. Instead of attempting to directly move some translation stuff or anything it probably is better to just delete wrench here when time comes and then if do what's needed in wrench repo if anything. It is git so even after deletion you just can go grab what's needed.

**Comment by OgelGames** [comment]
I'm working on this.
