### ISSUE TITLE
Confused about water turbine

### ISSUE THREAD

**Issue by spacekookie** [mt-mods/technic#256]
Hey! I'm pretty new to minetest and technic and confused about the "water turbine" item. In my game it's extremely easy to craft (4 sticks + 1 iron ingot) which doesn't seem to line up with the recipe for "hydro turbine" that I found in the code.

Is this another mod adding an item? Is there maybe some weird interaction between items?

**Comment by wsor4035** [comment]
pretty sure your looking at the mesecon water turbine

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/147412808-9a96e66a-a285-4f2d-9fbe-ed217a004ba4.png)
mesecon left, technic right (has two)

**Comment by spacekookie** [comment]
Ooh! Thanks for the quick reply! Oh so the hydro generator is the same as "hydro_turbine" in the code?

**Comment by wsor4035** [comment]
right https://github.com/mt-mods/technic/blob/bc9a7759f3d902d2c72cd2763fe08e0e9fce4340/technic/machines/MV/hydro_turbine.lua and https://github.com/mt-mods/technic/blob/bc9a7759f3d902d2c72cd2763fe08e0e9fce4340/technic/machines/LV/water_mill.lua

**Comment by spacekookie** [comment]
Ooh okay. Thanks for clarifying it
