### ISSUE TITLE
LV lamp light nodes blocking vision

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#262]
> Gimble: Also have you noticed the LV lamps cause strange clipping issues? I am using the 5.5.0 client, here I will show you.

![image](https://user-images.githubusercontent.com/50966843/154464085-093c5149-1936-4d91-80f0-e5c88bbc18a1.png)

![image](https://user-images.githubusercontent.com/50966843/154463791-54d567bf-22d2-4be1-bf57-b8b48480d012.png)

**Comment by S-S-X** [comment]
Graphics configuration might also have something to do with it... there's been other somewhat similar problems that only manifest when you're using certain configuration. I've not yet tested anything..

**Comment by BuckarooBanzay** [comment]
This might also be some kind of occlusion-culling "feature" that misinterprets the airlike nodes as solids (had to disable that in a few mods myself too because of false-positives) might also be a multicraft thing...
