### ISSUE TITLE
Remove frames

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#263]
https://github.com/mt-mods/technic/blob/master/technic/machines/other/frames.lua

Should not be part of technic mod and should be moved to separate mod or removed.

Note also that while some functionality for frames do work some other stuff will cause crash and reason seems to be unfinished code.

**Comment by OgelGames** [comment]
👍 it's basically a forgotten relic at this point :P (I don't even know what it was supposed to do)

**Comment by OgelGames** [comment]
Did a little searching to find out what frames were actually meant for, and found a good explanation by VanessaE on technic's forum page: https://forum.minetest.net/viewtopic.php?p=190492#p190492

> Here's how they work:
> - Build a platform or a small structure with the frames, as needed. Along the bottom or on one side, run a line of frames along the axis you want the structure to move in. I'll call this your "drive line".
> - Place a motor on the ground, directly up against your structure, so that the motor's arrows touch one of the frames in the drive line. Use the screwdriver to adjust the orientation of the arrows so that they point in the direction you want everything to move.
> - Run a mesecons wire to the motor.
> - Send a single high pulse down that wire to activate the motor. All of the frames will move one meter in the direction of the motor's arrow. Anything you place on, against, or under the frames will move with them (other than the motor that's driving them), except:
> - If you punch on a frame, the side you punched will toggle open or closed. A closed side (shows a solid texture with an X-shaped wooden pattern) won't move the objects that are placed against that side. Each of the six sides operates independently.
> - If you try to push part of your apparatus up against something, and it's a closed frame side or a non-frame object that makes contact with that something, the apparatus will stop moving there. If it's an open frame side that makes contact, the object that's in the way will become attached to the apparatus and will move along with it.
> - Frames won't move if there's a mesecons wire or other signal directly under them or next to them, so be sure you connect to your motor in such a way as to keep the drive signal mesecons wires away from the apparatus. Wires on TOP of the apparatus are treated like other objects and will move with it; mesecons circuits can be carried by the frames and will behave normally, but I'm not sure how "active" they're allowed to be.
> 
> The frames will only move by way of a motor if they're in contact with the arrows on the motor. Although it's not necessary, typically, you will have a Lua Controller handling the movement of the apparatus. You might even have a nodebreaker and a deployer at the end of the drive line near the motor, controlled by the LuaC so that they add and remove extra frames at the end of the line as your structure moves back and forth.

They still don't belong in technic though, and if they were going to be made into a separate mod they would need to be rewritten. If anyone wants to do anything with frames they can just look back in the git history.
