### ISSUE TITLE
Add particle effects

### ISSUE THREAD

**Issue by thomasrudin** [mt-mods/technic#27]
## Nodes

* [ ] `technic:nuclear_reactor_active` blue particles (Cherenkov radiation in water)

**Comment by OgelGames** [comment]
Looks like this was implemented in https://github.com/mt-mods/technic/commit/c0e05dbc8661b3be650f3e1cb60ba6c9ac09ebdc :wink:

**Comment by BuckarooBanzay** [comment]
oh, right, forgot to close :)

**Also**: thanks for this: https://github.com/pandorabox-io/pandorabox_custom/commit/36a79b4f5ccd26da57b1e5ec6b166ba09f9ab9fe looks like there are still some broken tubes... 😕
