### ISSUE TITLE
Upstream compat

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#272]
I think for the full compatibility to the upstream `technic` we are missing the following PR's:
(this is just to keep track of them)

* [x] https://github.com/minetest-mods/technic/pull/600
* [x] https://github.com/minetest-mods/technic/pull/592
* [x] https://github.com/minetest-mods/technic/pull/574 (not sure about that one, might already be in here)
* [ ] https://github.com/minetest-mods/technic/commit/349676f2438eda29488295f36f829518d1724275 CNC: Fix startup error and texture warnings

**Comment by OgelGames** [comment]
Also https://github.com/minetest-mods/technic/commit/349676f2438eda29488295f36f829518d1724275

**Comment by S-S-X** [comment]
Machine infotext thing is already here #207
