### ISSUE TITLE
Cherry picks from hume2's repo

### ISSUE THREAD

**Issue by thomasrudin** [mt-mods/technic#28]
* [ ] Forcefield shapes and perf improvements: https://gitlab.com/h2mm/technic/-/commit/b416407c2d14ed3cfef92084b375f6653e6b140a
* [ ] 6 Output slots on machines: https://gitlab.com/h2mm/technic/-/commit/38787f9aa307ad5c029e89bc40419c752e4cff72
* [x] network stuff (should be already in here): https://gitlab.com/h2mm/technic/-/commit/2cd2093b337250de8f8ece1bbebe1dbd78f95e5d
* [ ] ~~drawers digging (https://gitlab.com/h2mm/technic/-/merge_requests/37/diffs)~~

**Comment by BuckarooBanzay** [comment]
tried to cherry-pick the commits but the branches diverged too much :confounded:
if there is interest in the first two points (forcefield shapes, 6 output slots) feel free to reopen a separate issue
