### ISSUE TITLE
Radiation damage(reopening issue  #29)

### ISSUE THREAD

**Issue by zbx-pandorabox** [mt-mods/technic#30]
Hi, I finally spend some time for careful testing of rad dmg. There is imo problem with calling function 'throttle' from 'technic\technic\util\throttle.lua' during registering abm for dmg with label 'Radiation damage'(action = throttle(100, dmg_abm)). With this function rad dmg don't work. Minetest-mods\technic mod use there 'action = dmg_abm', this working. For softening damage is imo using 'chance' enough. 
Default settings of max_lag to 1.5 in function dmg_abm is imo too low.

**Comment by BuckarooBanzay** [comment]
New stategy (feature):

* new setting `technic.throttle_radiation_damage` (default false) for optional radiation damage limiting depending on lag
