### ISSUE TITLE
crafting circular dependency

### ISSUE THREAD

**Issue by imre84** [mt-mods/technic#313]
Hello, correct me if I'm wrong but as far as I can tell, in order to have a grinder I need coal powder, but in order to have coal powder I need to have a grinder.

I think there might be three solutions to the problem:
1. make mining to give coal powder instead of coal lump to the player (I'd make it give 2 coal dusts with very low probability)
2. make the alloying work with lumps as well
3. add a crafting recipe like 2 coal lumps=1 coal dust

all in all I like the third solution the best

**Comment by S-S-X** [comment]
You do not need coal dust to build grinder Unless you've somehow removed or replaced Technic worldgen.
For cast iron use cooking recipe (other recipe should be removed but wont prevent crafting, just not needed).

Just machine casing / cable and few simple items like diamond and was it marble.

**Comment by OgelGames** [comment]
> other recipes should be removed

#311 fixes that. It's amazing how many players have been confused by that recipe.
