### ISSUE TITLE
Which version of minetest ?

### ISSUE THREAD

**Issue by d-stephane** [mt-mods/technic#36]
Which version of minetest does this version of the mod work with ? (sorry for my bad english)

**Comment by BuckarooBanzay** [comment]
it works with 5.0+ but *could* work with older version (0.4.x) untested though...

**Comment by d-stephane** [comment]
Not 5.1 ou 5.2 ? Just 5.0 ?

**Comment by BuckarooBanzay** [comment]
> Not 5.1 ou 5.2 ? Just 5.0 ?

5.0+ means 5.1 and 5.2, 5.3, etc...

**Comment by d-stephane** [comment]
I just tested with 5.2 everything works
