### ISSUE TITLE
Allow machines to conduct digiline to all directions

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#43]
Digiline HV cable was added and it works fine... when you do not connect it to the machines from below.

Machines do not conduct downwards at all but they should if there is digiline cable connected.

Simplest is to just change digiline rules for machines but if digiline connection should be made only for digiline cables then rules should be changed depending on cable connection but only for rules that affect upwards and downward conductivity.

TBD, how machines should conduct digiline messages?
Some possible solutions:

- [x] Any existing and downwards.
- [ ] Any existing, downwards and upwards.
- [ ] Any existing and dynamic based on attached cables.
- [ ] Any existing and custom rules based on machine type.
- [ ] Any direction for all machines.

**Comment by BuckarooBanzay** [comment]
My vote is on " Any direction for all machines."

Reasoning:
* It does not affect performance
* Makes more sense (why wouldn't it conduct up and down?)
* Normally there should be enough gaps between digiline circuitry to prevent compatiblity issues with current builds

From what i can tell there aren't that much machines anyway that use digilines currently:
```
# grep digiline . -R | cut -d":" -f1 | sort -u

./HV/cables.lua
./HV/forcefield.lua
./HV/nuclear_reactor.lua
./register/battery_box.lua
./supply_converter.lua
./switching_station.lua
```

**Comment by S-S-X** [comment]
Something like
```
rules = {
	{x =  1,y =  0,z =  0}, {x = -1,y =  0,z =  0}, -- along x (beside)
	{x =  0,y =  1,z =  0}, {x =  0,y = -1,z = 0}, -- along y (above, below)
	{x =  0,y =  0,z =  1}, {x =  0,y =  0,z = -1}, -- along z (beside)
}
```

Should probably be merged with current rules.

Current rules used by switching station and probably by all other machines, digilines mod preset:
```
digilines.rules.default = {
  {x=1,  y=0,  z=0}, {x=-1, y=0,  z=0}, -- along x (beside)
  {x=0,  y=0,  z=1}, {x=0,  y=0,  z=-1}, -- along z (beside)
  {x=1,  y=1,  z=0}, {x=-1, y=1,  z=0}, -- 1 node above along x (diagonal)
  {x=0,  y=1,  z=1}, {x=0,  y=1,  z=-1},  -- 1 node above along z (diagonal)
  {x=1,  y=-1, z=0}, {x=-1, y=-1, z=0}, -- 1 node below along x (diagonal)
  {x=0,  y=-1, z=1}, {x=0,  y=-1, z=-1}, -- 1 node below along z (diagonal)
}
```

> My vote is on " Any direction for all machines."

Was thinking a bit about that and agree for most part but maybe not upwards...

Maybe remove rule that conducts upwards from most machines and only add that for supply converter? Or even leave it out completely.

**Comment by BuckarooBanzay** [comment]
> Was thinking a bit about that and agree for most part but maybe not upwards...
>
> Maybe remove rule that conducts upwards from most machines and only add that for supply converter? Or even leave it out completely.

Leaving the rule out completely would make it consistent, so: :+1:

**Comment by S-S-X** [comment]
Added by taking default rules and adding downwards direction, tested with switching station and very simple setup.
