### ISSUE TITLE
disable quarry-limit depending on lag

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#48]
per-user-quarry limit of 10 nodes, should be ok to lift temporarily if the lag allows it

**Comment by OgelGames** [comment]
Wouldn't it be better to simplify/rewrite some of the code for the quarry, to make it more efficient? I'd be happy to do it, and I probably already would have if it wasn't for this: https://github.com/BuckarooBanzay/enhanced_quarry :confused:

**Comment by BuckarooBanzay** [comment]
> Wouldn't it be better to simplify/rewrite some of the code for the quarry, to make it more efficient, instead of adding even more code around it? I'd be happy to do it, and I probably already would have if it wasn't for this: https://github.com/BuckarooBanzay/enhanced_quarry confused

The "normal" quarry will stay either way. The `enhanced_quarry` mod has currently some issues with face-direction stuff (and the missing motivation to finish it).

I'm also thinking about a new class/level of power-generation i may start first, something along the lines of fusion-power to feed the ~~beast~~ enhanced_quarry (still HV tier though).

If you have improvements on the normal technic quarry please go ahead, there are no plans to remove it. Also: sorry for the workaround mess with the limits and such, it just piled up like that... :shrug:

**Comment by S-S-X** [comment]
As there is some work done with enhanced_quarry it would be good to keep regular quarry functionally as is without any added features and only work on optimization there.
Then enhanced_quarry should be one receiving new features.

Actual code for core function which is digging nodes could also be provided through some kind of basic quarry API in a way that enhanced_quarry and whatever_quarry could benefit from actual optimizations done there.

Just simple caching of working area would make it a lot better and providing API that can accept precalculated digging matrix (like cnc matrix) would make it a lot cheaper and would still allow digging weird shapes if some enhanced_cnc_quarry wants to dig weird shapes while also making digging a lot more efficient.

Downside of heavy caching is that there must be additional checks for special events like jumping quarry to other location but API could also provide required reset methods.

**Comment by OgelGames** [comment]
Good to know where everything sits regarding the `enhanced_quarry`, I wasn't quite sure if it was going to replace the "normal" quarry, which is why I was hesitant to work on the existing code.

> it would be good to keep regular quarry functionally as is without any added features and only work on optimization there.
> Then enhanced_quarry should be one receiving new features.

That was what I was planning, to simplify and optimize the existing functionality, without adding or removing anything.

> I'm also thinking about a new class/level of power-generation i may start first, something along the lines of fusion-power

I like the sound of that :smile:

**Comment by OgelGames** [comment]
Seeing as I haven't mentioned anything about how the quarry optimization/improvement is going, I thought I'd do some basic benchmarking using `minetest.get_us_time()` to compare the CPU usage of the existing quarry code with the current optimized code

The tests were 10 quarries on a single network, with max dig radius, lined up in a row digging down to a depth of 10 nodes. (all times in μs)

|  | Min | Max | Avg | Total usage |
| :--- | ---: | ---: | ---: | ---: |
| Old code | 31 | 10,621 | 489.12 | 2,210,846 |
| New code | 28 | 2,370 | 157.49 | 880,374 |

Additionally, the old quarries triggered the polyfuse 5 times during testing, while the new quarries didn't trigger it at all.

**Comment by BuckarooBanzay** [comment]
Wow, thats a 2.5 times performace increase if i'm not mistaken! :astonished:
How did you achieve that?
How much of the old ~~crap~~ code did you rip out :smile:?

**Comment by OgelGames** [comment]
> How did you achieve that?
> How much of the old ~crap~ code did you rip out ?

I basically rewrote all the digging code, using a different method of digging, so that there are less calculations per cycle.

I used the same method as the `techpack` quarry, but adapted for a variable radius: https://github.com/joe7575/techpack/blob/master/tubelib_addons1/quarry.lua

Put simply, instead of recalculating the dig position every cycle, it just moves the last dig position (which gets saved in the metadata) one node at a time, in a predefined pattern.

**Comment by BuckarooBanzay** [comment]
this is not valid anymore, closing. Thanks @OgelGames for the quarry improvements :tada:
