### ISSUE TITLE
add to contentdb

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#66]
`technic_redo` / `technic_ng` ?

**Comment by OgelGames** [comment]
Not quite sure, but `technic_plus` might make more sense, because it's not a complete rewrite (`technic_redo`), and it's not a new system (`technic_ng`).

**Comment by BuckarooBanzay** [comment]
done: https://content.minetest.net/packages/BuckarooBanzay/technic_plus/

i would've liked a generic name like `mt-mods` instead of my name, but it will do for now
