### ISSUE TITLE
Supply converters can not be disabled via formspec

### ISSUE THREAD

**Issue by groxxda** [mt-mods/technic#71]
https://github.com/minetest/minetest/issues/10180 triggers the following bug for supply converters:

- If the user disables a supply converter via the formspec, the enabled value is set to 0, effectively clearing the value.
- During the next run step, the "backwards compatibility" code in https://github.com/mt-mods/technic/blob/6a9cf6da27afd4f33283934507085a00b6cbda88/technic/machines/supply_converter.lua#L132-L138 runs the on_construct function, which in turn resets enabled to 1.

This will be fixed by https://github.com/minetest/minetest/pull/10183 . In the meantime, the bug could be resolved by replacing the backward compatibility code with
```
local enabled       = meta:get_int("enabled") == 1
```

**Comment by BuckarooBanzay** [comment]
I added your temporary workaround here:
https://github.com/mt-mods/technic/commit/f14faa668010f2175dfaff8525dbffd25bf90d6e

**Comment by groxxda** [comment]
I'm sorry if I was unclear, the temporary workaround needs to replace the entire code quoted in the initial post

```diff
diff --git a/technic/machines/supply_converter.lua b/technic/machines/supply_converter.lua
index 667f683..f768924 100644
--- a/technic/machines/supply_converter.lua
+++ b/technic/machines/supply_converter.lua
@@ -129,14 +129,10 @@ local run = function(pos, node, run_stage)
        local machine_name  = S("Supply Converter")
        local meta          = minetest.get_meta(pos)
        local enabled       = meta:get_string("enabled")
-       if enabled == "" then
-               -- Backwards compatibility
-               minetest.registered_nodes["technic:supply_converter"].on_construct(pos)
-               enabled = true
-       else
-               -- compatibility case for #71
-               enabled = meta:get_int("enabled") == 1
-       end
+
+       -- compatibility case for #71
+       enabled = meta:get_int("enabled") == 1
+
        enabled = enabled and (meta:get_int("mesecon_mode") == 0 or meta:get_int("mesecon_effect") ~= 0)
        local demand = enabled and meta:get_int("power") or 0
```

**Comment by BuckarooBanzay** [comment]
ah, this makes more sense, sorry for that. I refactored the code a bit: https://github.com/mt-mods/technic/commit/6f83cb892c5d8816862b0ba4816406f6d31bc54f

**Also**: i sent you an invite to this repo, it should make contributing easier (no pressure to contribute/maintain though)
