### ISSUE TITLE
switching station gets overloaded too often

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#77]
Yesterday I built a spaceship with a few cannons and a jumpdrive, and I experienced a lot of issues with switching station overloading, both while building and when using it. 

The SS got overloaded almost every time I added something to the network, and also overloaded a few times when I hadn't even touched the network.

Overloading also happened every time I jumped the ship, which was annoying when I was fighting skylord in the warzone. (who also had all the same issues)

By what I've seen (search for "overload" in discord), other players are equally annoyed and confused by the SS overloading, so I'm wondering if there is a way to make it better, or if it should be removed in favor of some other fix for the network bugs/cheats.

- [x] SS got overloaded almost every time I added something to the network
- [ ] Overloading also happened every time I jumped the ship
   - see PR #74 comments and mt-mods/jumpdrive#47
   - there's few things that might benefit from creating another ticket for that issue
- [x] what I've seen (search for "overload" in discord), other players are equally annoyed.
   - SX: Every case I checked was actually using cheats...

@S-S-X

**Comment by S-S-X** [comment]
Known problem and was mentioned in PR

**Comment by S-S-X** [comment]
Quick fix for adding machines would be adding network id early, currently it is only done during building network and is missing for newly added machines/cables. This causes newly added machine seen as machine not belonging to network which then causes network cache reset to check again if network is legit.

**Comment by BuckarooBanzay** [comment]
> Quick fix for adding machines would be adding network id early, currently it is only done during building network cache and is missing for newly added machines/cables. This causes newly added machine seen as machine not belonging to network which then causes network cache reset to check again if network is legit.

No pressure @S-S-X most of the things _still_ work right now :smirk:

**Comment by S-S-X** [comment]
> No pressure @S-S-X most of the things still work right now

Meanwhile you might be able to use another bug #76 to build networks that execute a lot more often... :smile:

**Comment by S-S-X** [comment]
Linking also PR #74 as there was some things written out that needs to get better.

Most important points:
* Behavior is still a bit undefined when network contains more than 2 switching station firing ABM events
   - Add support for linked switching stations (improve caching, share net id), #75 would also be very nice to have for this (no direct dependency).
   - Even just 2 switching stations can cause overload (through reactivation / changing active switch) because both have different network id.
* Network will be invalid after switching station is moved to another location
   - Create ticket for jumpdrive mod?
   - Or attempt to fix with hack that checks previous location and if station is missing just let it rebuild cache without overload trigger?
   - Or fix with some on_move callback (whatever moves it should call this function)?

**Comment by S-S-X** [comment]
Also to say a word on
> By what I've seen (search for "overload" in discord), other players are equally annoyed and confused by the SS overloading

I've checked few complaints and all were cheating either with multi network generators or more often run frequency multiplication.

**Comment by S-S-X** [comment]
related https://github.com/mt-mods/jumpdrive/issues/47

**Comment by BuckarooBanzay** [comment]
> related [mt-mods/jumpdrive#47](https://github.com/mt-mods/jumpdrive/issues/47)

Hmm, yes, about that: i wasn't sure if that api would cover all use-cases..
In your opinion, would something like this be enough for now:

```lua
-- function on the node-definition
on_movenode = function(from, to)
 -- from/to are positions
 -- additional infos can be added later in a third parameter
end
```

The function would be called "in-between" jumps, at the time when both source and destination have the same contents.
Metadata should be available to read from the source and write to the destination.

I also think i'm adding a `pcall` fence to this so errors in this function don't result in an invalid node-state or item-duplications.

**Comment by S-S-X** [comment]
> The function would be called "in-between" jumps, at the time when both source and destination have the same contents.
Metadata should be available to read from the source and write to the destination.

I think this would cover it, what has to be done is:
* Destroy caches from source coordinates, setting cache container with source network id to nil
* Either update metadata on target coordinates by adding offset to network id and writing new network id to nodes or simply removing network id metadata (will be added back by next switch run, starts fresh new network).

There optionally cache could also be moved directly without rebuilding (no world / metadata reads/writes) but that probably makes fixing partially jumped networks a lot harder. If cache is not reused then I don't actually see any other reason to keep/translate metadata to new coords other than avoiding 1 extra metadata write per node.

**Comment by S-S-X** [comment]
That commit probably fixes (through using correct network id when adding nodes)
> overloaded almost every time I added something to the network

**Comment by OgelGames** [comment]
Seems to work better while building, but now there is another bug: changing the SS location on a network causes a overload loop.

I was able to reproduce it consistently by placing two cables next to each other, placing a SS on one (which works), then removing and placing the SS on the other cable.

**Comment by S-S-X** [comment]
@OgelGames still experimenting and testing here, fixed things on local and adding bug comments to commit.

**Comment by S-S-X** [comment]
> I was able to reproduce it consistently by placing two cables next to each other, placing a SS on one (which works), then removing and placing the SS on the other cable.

I think now after other stuff is there this could be improved a bit by cleaning old caches if previous switching station was removed when switching station `on_construct` is called. Already added check if newly added switch can be set inactive immediately after placement (https://github.com/mt-mods/technic/pull/80/commits/b131e3f3439ad0f3c3cb2ca3ebd05cd4ca127ca6).
