### ISSUE TITLE
LV and MV digiline cables

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/technic#97]
v1

What do you guys think about these possible textures for LV and MV digiline cables?

![technic_lv_digi_cable](https://user-images.githubusercontent.com/161979/95642044-52818180-0aa6-11eb-837f-137421ee0977.png)
![technic_lv_digi_cable_wield](https://user-images.githubusercontent.com/161979/95642045-531a1800-0aa6-11eb-8c1b-ab7ece712f39.png)
![technic_mv_digi_cable](https://user-images.githubusercontent.com/161979/95642046-531a1800-0aa6-11eb-872c-f9cdbcc4de3d.png)
![technic_mv_digi_cable_wield](https://user-images.githubusercontent.com/161979/95642047-53b2ae80-0aa6-11eb-83d9-08b6787b013d.png)

I originally was going for just a horizontal blue stripe. It looked good for the wield image but I was sceptical it would work for placed cables. So I went with the stripes with highlight on only one side.

**Comment by SwissalpS** [comment]
Here is the horizontal version. Have not yet tested to see how they connect.
![technic_lv_digi_cable2](https://user-images.githubusercontent.com/161979/95642510-49de7a80-0aa9-11eb-9d6d-16804a259d4d.png)
![technic_lv_digi_cable_wield2](https://user-images.githubusercontent.com/161979/95642515-4d720180-0aa9-11eb-9251-3a5556d39463.png)
![technic_mv_digi_cable2](https://user-images.githubusercontent.com/161979/95642516-4e0a9800-0aa9-11eb-833a-fa618764e97c.png)
![technic_mv_digi_cable_wield2](https://user-images.githubusercontent.com/161979/95642518-4ea32e80-0aa9-11eb-9ba8-dcf869c66c8d.png)

**Comment by SwissalpS** [comment]
![digihorcables](https://user-images.githubusercontent.com/161979/95642710-83fc4c00-0aaa-11eb-9e87-1e2ce4f10126.png)

**Comment by SwissalpS** [comment]
vs
![aaa](https://user-images.githubusercontent.com/161979/95642855-87440780-0aab-11eb-8398-145f12798900.png)

**Comment by SwissalpS** [comment]
![technic_lv_digi_cable3](https://user-images.githubusercontent.com/161979/95642920-16511f80-0aac-11eb-98d7-0d0a0dfbaac2.png)
![technic_mv_digi_cable3](https://user-images.githubusercontent.com/161979/95642924-194c1000-0aac-11eb-9da3-c8d3105791da.png)
![aa](https://user-images.githubusercontent.com/161979/95642994-9081a400-0aac-11eb-88b6-59fb04dbc236.png)

**Comment by SwissalpS** [comment]
![technic_lv_digi_cable4](https://user-images.githubusercontent.com/161979/95643138-77c5be00-0aad-11eb-950d-bde057d00787.png)
![technic_mv_digi_cable4](https://user-images.githubusercontent.com/161979/95643139-785e5480-0aad-11eb-9950-19d8aaa393a5.png)
![a4](https://user-images.githubusercontent.com/161979/95643226-3e418280-0aae-11eb-9f59-218e290004fa.png)

**Comment by SwissalpS** [comment]
![technic_lv_digi_cable5](https://user-images.githubusercontent.com/161979/95643259-67621300-0aae-11eb-92c2-4938a7155797.png)
![technic_mv_digi_cable5](https://user-images.githubusercontent.com/161979/95643261-67faa980-0aae-11eb-80a1-5a2905f5d49e.png)
![aa5](https://user-images.githubusercontent.com/161979/95643330-dc354d00-0aae-11eb-979f-7ae55dd13713.png)

**Comment by SwissalpS** [comment]
![aa5a](https://user-images.githubusercontent.com/161979/95643447-844b1600-0aaf-11eb-97d5-702778573514.png)

**Comment by S-S-X** [comment]
In my opinion, these are best:

> ![technic_lv_digi_cable4](https://user-images.githubusercontent.com/161979/95643138-77c5be00-0aad-11eb-950d-bde057d00787.png)
> ![technic_mv_digi_cable4](https://user-images.githubusercontent.com/161979/95643139-785e5480-0aad-11eb-9950-19d8aaa393a5.png)

I do like these simple ones most ^^
Very nice that you made so many versions, to select my opinion also for second place it would be this:

> ![technic_lv_digi_cable5](https://user-images.githubusercontent.com/161979/95643259-67621300-0aae-11eb-92c2-4938a7155797.png)
> ![technic_mv_digi_cable5](https://user-images.githubusercontent.com/161979/95643261-67faa980-0aae-11eb-80a1-5a2905f5d49e.png)

**Comment by SwissalpS** [comment]
feel free to implement whichever combination you like :)

**Comment by OgelGames** [comment]
I like the last one, just because it could be cool for decorative purposes too, but I'd be fine with either of the two @S-S-X picked out.

**Comment by 6r1d** [comment]
V5 is the best so far, imo. V4 is nice, as well.

**Comment by SwissalpS** [comment]
LV v5 and MV v4 are my favs.

**Comment by SwissalpS** [comment]
... then a bunch of cable plates could look something like this:
![image](https://user-images.githubusercontent.com/161979/95645687-d432d880-0ac1-11eb-877f-1bb7809302cb.png)

**Comment by SwissalpS** [comment]
for prosperity some 'fails'

v4d
===
![technic_lv_digi_cable4d](https://user-images.githubusercontent.com/161979/95647531-71950900-0ad0-11eb-9876-b20f94e15692.png)
![technic_mv_digi_cable4d](https://user-images.githubusercontent.com/161979/95647538-735ecc80-0ad0-11eb-9296-ef3f3887dc6c.png)

v4z
===
![technic_lv_digi_cable4z](https://user-images.githubusercontent.com/161979/95647533-722d9f80-0ad0-11eb-9f21-529fb2173e42.png)

v5d
===
![technic_lv_digi_cable5d](https://user-images.githubusercontent.com/161979/95647534-722d9f80-0ad0-11eb-8eb8-177417cc6a57.png)
![technic_mv_digi_cable5d](https://user-images.githubusercontent.com/161979/95647541-735ecc80-0ad0-11eb-8e3b-a609cba42ecc.png)

v6.8
===
![technic_lv_digi_cable6_8](https://user-images.githubusercontent.com/161979/95647536-72c63600-0ad0-11eb-994f-d24fe723139f.png)
v6.16
====
![technic_lv_digi_cable6_16](https://user-images.githubusercontent.com/161979/95647537-72c63600-0ad0-11eb-87f3-d5bb183aec21.png)

**Comment by SwissalpS** [comment]
the wield images to v4 and v5

v4
===
![technic_lv_digi_cable_wield4](https://user-images.githubusercontent.com/161979/95694170-c059b480-0c30-11eb-8ad2-b9b4fbe82929.png)
![technic_mv_digi_cable_wield4](https://user-images.githubusercontent.com/161979/95694175-c2bc0e80-0c30-11eb-881c-1cbd67bc8f67.png)

v5
===
![technic_lv_digi_cable_wield5](https://user-images.githubusercontent.com/161979/95694174-c2237800-0c30-11eb-9a41-f71658542ae2.png)
![technic_mv_digi_cable_wield5](https://user-images.githubusercontent.com/161979/95694176-c2bc0e80-0c30-11eb-8af3-9e1fdb77ee7d.png)

**Comment by SwissalpS** [comment]
here the messy gimp xcf files I used
[digi_cables_lv_mv.zip](https://github.com/mt-mods/technic/files/5362495/digi_cables_lv_mv.zip)

**Comment by BuckarooBanzay** [comment]
nice work @SwissalpS :tada:
