### ISSUE TITLE
sonic screwdriver does not call "on_rotate"

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#98]
Unlike the builtin `screwdriver` mod

**Comment by S-S-X** [comment]
one of our most important feature :rofl: 

  - <details><summary>#</summary>quick, someone try to sneak in from behind and mark this as invalid</details>

**Comment by OgelGames** [comment]
Yes, this should not be changed, it might even be intentional just like not calling `can_dig` is:
https://github.com/mt-mods/technic/blob/0f886d629d94634e9e343fb2e44c79c157c224eb/technic/tools/sonic_screwdriver.lua#L41

**Comment by BuckarooBanzay** [comment]
oh, nevermind then :+1:
